### ISSUE TITLE
Fix special chars in Menu Name

### ISSUE THREAD

**Issue by schmunk42** [dmstr/yii2-pages-module#15]
Rooms & Rates

becomes

    Rooms &amp;amp; Rates

**Comment by Quexer69** [comment]
It is caused by

https://github.com/kartik-v/yii2-tree-manager/blob/master/models/Tree.php#L62

wich does this validation

https://github.com/kartik-v/yii2-tree-manager/blob/master/models/TreeTrait.php#L117

I set html encode name to `false` in

https://github.com/dmstr/yii2-pages-module/blob/master/models/BaseTree.php#L286

no you can use any chars in page names.

update available in release [0.21.2](https://github.com/dmstr/yii2-pages-module/releases/tag/0.21.2)
